# Generated by Django 6.0.6 on 2026-07-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
        ('users', '0002_user_email_cimetiere_user_statut_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cimetiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='etablissements.cimetiere'),
        ),
    ]
