# Generated by Django 6.0.6 on 2026-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cimetiere',
            name='ville',
            field=models.CharField(default='Brazzaville', max_length=100),
        ),
    ]
