# Generated by Django 6.0.6 on 2026-07-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveaux', '0002_initial'),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caveau',
            name='zone',
        ),
        migrations.AddField(
            model_name='caveau',
            name='bloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='etablissements.bloc'),
        ),
        migrations.AddField(
            model_name='caveau',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=75000, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
