# Generated by Django 6.0.6 on 2026-06-14 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('mfa', 'Code MFA'), ('reservation', 'Confirmation réservation'), ('validation', 'Validation réservation'), ('facture', 'Facture générée'), ('paiement', 'Paiement reçu'), ('echeance', 'Échéance concession'), ('retard', 'Retard de paiement'), ('exhumation', 'Demande exhumation'), ('seuil_critique', 'Seuil places critique')], max_length=30)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('envoye_par_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
